import { Injectable, inject, signal, computed, effect } from '@angular/core';
import {
  AnalyticsAlert,
  AnalyticsEvent,
  AnalyticsMetric,
  AnalyticsTimeRange,
  GpAnalyticsConfig,
} from '../models/analytics.models';
import { GP_ANALYTICS_CONFIG } from '../tokens/analytics.tokens';

export interface MetricAlertThresholdRule {
  id: string;
  metricId: string;
  condition: 'gt' | 'lt' | 'eq' | 'gte' | 'lte';
  threshold: number;
  message: string;
  severity: 'info' | 'warning' | 'error' | 'critical';
}

@Injectable({
  providedIn: 'root',
})
export class GpAnalyticsService {
  private readonly config = inject(GP_ANALYTICS_CONFIG, { optional: true }) ?? {
    appName: 'Generated Pixel Analytics',
    enabled: true,
  };

  /** Reactive signal of all recorded events in memory buffer */
  readonly events = signal<AnalyticsEvent[]>([]);

  /** Reactive signal of current tracked metrics */
  readonly metrics = signal<Map<string, AnalyticsMetric>>(new Map());

  /** Reactive signal of active alerts generated by rules/thresholds */
  readonly alerts = signal<AnalyticsAlert[]>([]);

  /** Active time range for queries/visualizations */
  readonly activeTimeRange = signal<AnalyticsTimeRange>(
    this.config.defaultTimeRange ?? '24h',
  );

  /** Active tracking status */
  readonly isTrackingEnabled = signal<boolean>(this.config.enabled ?? true);

  /** Registered threshold rules for automatic alert generation */
  readonly rules = signal<MetricAlertThresholdRule[]>([]);

  /** Computed list of metrics array for easy UI looping */
  readonly metricList = computed(() => Array.from(this.metrics().values()));

  /** Computed counts */
  readonly totalEventsCount = computed(() => this.events().length);
  readonly activeAlertsCount = computed(() => this.alerts().filter((a) => !a.acknowledged).length);

  constructor() {
    if (this.config.debug) {
      effect(() => {
        console.log(`[gp-analytics] Events count: ${this.totalEventsCount()}`);
      });
    }
  }

  /**
   * Tracks an application event.
   */
  trackEvent<T extends Record<string, unknown> = Record<string, unknown>>(
    name: string,
    category: string = 'general',
    properties: T = {} as T,
    severity: AnalyticsEvent['severity'] = 'info',
  ): AnalyticsEvent<T> {
    const event: AnalyticsEvent<T> = {
      id: `evt-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
      name,
      category,
      properties,
      timestamp: new Date(),
      severity,
    };

    if (this.isTrackingEnabled()) {
      const maxBuffer = this.config.bufferSize ?? 200;
      this.events.update((current) => [event as unknown as AnalyticsEvent, ...current.slice(0, maxBuffer - 1)]);
    }

    return event;
  }

  /**
   * Registers a metric definition.
   */
  registerMetric(metric: AnalyticsMetric): void {
    this.metrics.update((current) => {
      const updated = new Map(current);
      updated.set(metric.id, { ...metric, updatedAt: new Date() });
      return updated;
    });
  }

  /**
   * Updates an existing metric's value and evaluates threshold rules.
   */
  updateMetric(
    metricId: string,
    newValue: number,
    options?: {
      changePercentage?: number;
      trend?: 'up' | 'down' | 'neutral';
      sparklinePoint?: number;
    },
  ): void {
    this.metrics.update((current) => {
      const existing = current.get(metricId);
      if (!existing) {
        return current;
      }

      const prev = existing.value;
      const sparkline = existing.sparkline ? [...existing.sparkline] : [];
      if (options?.sparklinePoint !== undefined) {
        sparkline.push(options.sparklinePoint);
        if (sparkline.length > 20) sparkline.shift();
      }

      const changePct =
        options?.changePercentage ??
        (prev !== 0 ? Math.round(((newValue - prev) / Math.abs(prev)) * 100 * 10) / 10 : 0);

      const trend =
        options?.trend ??
        (newValue > prev ? 'up' : newValue < prev ? 'down' : 'neutral');

      const updatedMap = new Map(current);
      updatedMap.set(metricId, {
        ...existing,
        previousValue: prev,
        value: newValue,
        changePercentage: changePct,
        trend,
        sparkline,
        updatedAt: new Date(),
      });

      return updatedMap;
    });

    this.evaluateRulesForMetric(metricId, newValue);
  }

  /**
   * Registers a threshold rule for automated alerting.
   */
  registerRule(rule: MetricAlertThresholdRule): void {
    this.rules.update((current) => [...current.filter((r) => r.id !== rule.id), rule]);
  }

  /**
   * Evaluates rules against a metric value.
   */
  private evaluateRulesForMetric(metricId: string, value: number): void {
    const matchingRules = this.rules().filter((r) => r.metricId === metricId);

    for (const rule of matchingRules) {
      let triggered = false;
      switch (rule.condition) {
        case 'gt':
          triggered = value > rule.threshold;
          break;
        case 'gte':
          triggered = value >= rule.threshold;
          break;
        case 'lt':
          triggered = value < rule.threshold;
          break;
        case 'lte':
          triggered = value <= rule.threshold;
          break;
        case 'eq':
          triggered = value === rule.threshold;
          break;
      }

      if (triggered) {
        this.createAlert({
          id: `alert-${rule.id}-${Date.now()}`,
          ruleId: rule.id,
          metricId,
          message: `${rule.message} (Value: ${value}, Threshold: ${rule.threshold})`,
          severity: rule.severity,
          timestamp: new Date(),
          triggerValue: value,
          threshold: rule.threshold,
          acknowledged: false,
        });
      }
    }
  }

  /**
   * Dispatches an alert.
   */
  createAlert(alert: AnalyticsAlert): void {
    this.alerts.update((current) => [alert, ...current.slice(0, 49)]);
  }

  /**
   * Acknowledges an alert by ID.
   */
  acknowledgeAlert(alertId: string): void {
    this.alerts.update((current) =>
      current.map((a) => (a.id === alertId ? { ...a, acknowledged: true } : a)),
    );
  }

  /**
   * Clears all alerts.
   */
  clearAlerts(): void {
    this.alerts.set([]);
  }

  /**
   * Sets the current active time range.
   */
  setTimeRange(range: AnalyticsTimeRange): void {
    this.activeTimeRange.set(range);
  }

  /**
   * Toggles tracking on/off.
   */
  setTracking(enabled: boolean): void {
    this.isTrackingEnabled.set(enabled);
  }
}
